### ISSUE TITLE
Prepopulate the Excel template for murine source metadata

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/documentation#57]
https://docs.sennetconsortium.org/libraries/ingest-validation-tools/schemas/source-murine/

We need to prepopulate the `metadata_schema_id` column with 44662059-aa73-4756-a4a7-990489ca2f43

**Comment by bhonick** [comment]
I'm not sure if this is a task for you or the CEDAR team in HuBMAP.

**Comment by maxsibilla** [comment]
Update the Excel link to point to https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/raw/main/source-murine/latest/source-murine.xlsx
