### ISSUE TITLE
Modify sankey diagram utilizing UBKG

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/documentation#73]
https://docs.sennetconsortium.org/data-sankey/

- [x] Utilize new `category` property from the UBKG [organs](https://ontology-api.dev.hubmapconsortium.org/organs?application_context=sennet) endpoint to get the grouped organ based on laterality
- [x] Add a new column that will come before `dataset_type` that will display the same top level hierarchy as in the portal (`modality` from the [assay classes](https://ontology-api.dev.hubmapconsortium.org/assayclasses?application_context=SENNET) endpoint

**Comment by libpitt** [comment]
1. hit Ingest API /assaytype => `description` from response is the `assay_displayname`
2. `dataset_type_hierarchy` => `modality` from UBKG (https://ontology-api.dev.hubmapconsortium.org/assayclasses?application_context=SENNET) where `value.assaytype` = Ingest API’s response `assaytype`
